# Generated by Django 5.1 on 2024-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='ideas',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AddField(
            model_name='xizmatlar',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
        migrations.AlterField(
            model_name='commites',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Published')], default='pb', max_length=10),
        ),
    ]
