# Generated by Django 5.1 on 2024-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articles_status_category_status_company_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commites',
            name='seen',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideas',
            name='seen',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='staj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xizmatlar',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
