# Generated by Django 5.1 on 2024-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_commites_seen_ideas_seen_team_staj_xizmatlar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xizmatlar',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
