# Generated by Django 5.1 on 2024-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_articles_seen_company_seen_team_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='xizmatlar',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
