# Generated by Django 5.1 on 2024-08-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_company_image_alter_ideas_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100, unique=True)),
                ('youremail', models.CharField(blank=True, max_length=100, null=True)),
                ('yourphone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('companyname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('iteananme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ideas')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['yourname'], name='home_messag_yournam_e821cb_idx')],
            },
        ),
    ]
